/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ar.nas.gui;

import javax.swing.JScrollPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author arif
 */
public class ConsequentParameterView extends javax.swing.JFrame {

    /**
     * Creates new form ConsequentParameterView
     */
    public ConsequentParameterView(double[][][] cp) {
        initComponents();
        setParameter(cp);
        this.setSize(580, 500);
    }

    //[nRule][nOutput][nInput+1]
    public void setParameter(double[][][] pp) {
        for (int i = 0; i < pp.length; i++) {
            
            String[][] row = new String[pp[i][0].length][1];
            for (int j = 0; j < pp[i][0].length; j++) {
                row[j][0] = String.valueOf(j+1);
            }
            TableModel tableModel1 = new DefaultTableModel(row, new String[] {"P"}) {
                @Override
                public Class getColumnClass(int columnIndex) {
                    return java.lang.String.class;
                }
                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };

            String[] column = new String[pp[i].length];
            for (int j = 0; j < pp[i].length; j++) {
                column[j] = String.valueOf(j+1);
            }
            Double[][] row1 = new Double[pp[i][0].length][pp[i].length];
            for (int j = 0; j < pp[i].length; j++) {
                for (int k = 0; k < pp[i][j].length; k++) {
                    row1[k][j] = pp[i][j][k];
                }
            }
            TableModel tableModel2 = new DefaultTableModel(row1, column) {
                @Override
                public Class getColumnClass(int columnIndex) {
                    return java.lang.Double.class;
                }
                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };
            
            JTable jTable1 = new javax.swing.JTable();
            jTable1.setModel(tableModel1);
            JTable jTable2 = new JTable();
            jTable2.setModel(tableModel2);
            jTable1.setBackground(jTable2.getTableHeader().getBackground());
            JViewport viewport = new JViewport();    
            viewport.setView(jTable1);
            viewport.setPreferredSize(jTable1.getPreferredSize());   
            JScrollPane jScrollPane1 = new JScrollPane();
            jScrollPane1.setRowHeaderView(viewport);
            jScrollPane1.setCorner(JScrollPane.UPPER_LEFT_CORNER, jTable1.getTableHeader());
            jScrollPane1.setViewportView(jTable2);
            JPanel jPanel1 = new JPanel();
            jPanel1.add(jScrollPane1);
            jTabbedPane1.addTab(String.valueOf(i+1), jPanel1);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
