/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arnas.gui;

import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author arif
 */
public class AttributesCorrelationFrame extends javax.swing.JFrame {

    /**
     * Creates new form AttributesCorrelationFrame
     */
    public AttributesCorrelationFrame(Double[][] correlation) {
        makeTableModel(correlation);
        initComponents();
    }
    
    TableModel tableModel1;
    TableModel tableModel2;
    JTable jTable1;
    
    private void makeTableModel(Double[][] correlation) {
        String[][] row = new String[correlation.length][1];
        for (int i = 0; i < row.length; i++) {
            row[i][0] = "X" + (i+1);
        }
        
        tableModel1 = new DefaultTableModel(row, new String[] {"Correlation"}) {
            @Override
            public Class getColumnClass(int columnIndex) {
                return java.lang.String.class;
            }
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        
        String[] column = new String[correlation[0].length+1];
        Double[][] row1 = new Double[correlation.length][correlation[0].length+1];
        for (int i = 0; i < correlation[0].length; i++) {
            column[i] = "Y" + (i+1);
        }
        column[correlation[0].length] = "AVG";
        
        for (int i = 0; i < row.length; i++) {
            double sum = 0.0;
            for (int j = 0; j < correlation[i].length; j++) {
                row1[i][j] = correlation[i][j];
                sum += Math.abs(correlation[i][j]);
            }
            row1[i][correlation[i].length] = sum / correlation[i].length;
        }
        
        tableModel2 = new DefaultTableModel(row1, column) {
            @Override
            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Attributes Correlation");

        jTable2.setModel(tableModel2);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable1 = new javax.swing.JTable();
        jTable1.setModel(tableModel1);
        jTable1.setBackground(jTable2.getTableHeader().getBackground());
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(70);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTable1.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );

        JViewport viewport = new JViewport();
        viewport.setView(jTable1);
        viewport.setPreferredSize(jTable1.getPreferredSize());
        jScrollPane2.setRowHeaderView(viewport);
        jScrollPane2.setCorner(JScrollPane.UPPER_LEFT_CORNER, jTable1.getTableHeader());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
